### ISSUE TITLE
struct field options should be at beginning of line

### ISSUE THREAD

**Issue by mikeal** [rvagg/js-ipld-schema#3]
Based on my last conversation with @warfork, the options for fields in a struct are now at the beginning of the line.

```
type myStruct struct {
   optional name String
   nullable size Int
   files Files # required
 }
```

The current schema parser wants them in the middle of the statement. I tried to write a patch for this myself but I’m hitting odd errors parsing `}` at the end of the statement. This may be related to the `// TODO: break these by newline || "}" (non-greedy match)` comment in the source.

**Comment by mikeal** [comment]
hey @warpfork, can you weigh in here, I can’t remember which of these is correct anymore (options in front or in the middle)?

**Comment by rvagg** [comment]
I don't recall exactly but maybe they were going into parens at the end along with the representation modifiers?

**Comment by mikeal** [comment]
I was wrong, this is actually correct, closing.
