### ISSUE TITLE
support for implicit syntax for default values

### ISSUE THREAD

**Issue by mikeal** [rvagg/js-ipld-schema#4]
The following schema:

```
type Permissions struct {
  sticky Bool (implicit: false)
  setuid Bool (implicit: false)
  setgid Bool (implicit: false)
}
```

Fails to parse with the following error:

```
SyntaxError: Expected "#", "}", [ \t\n\r], or [a-zA-Z0-9_] but "(" found.
```

**Comment by rvagg** [comment]
Done in v0.1.0 to match the current spec: `(implicit "false")`, but they still come out as `"default": false` in the parsed form, need to change that in the spec before I change it here.
